language: dart

dart: stable

env:
  global:
    - LIBS="bin lib test"

script:
  - dartanalyzer --fatal-warnings $LIBS #  --fatal-infos --fatal-hints
  - dartfmt -n --set-exit-if-changed $LIBS
  - pub run test -x integration
  - dart test/e2e_test.dart

cache:
  directories:
    - $HOME/.pub-cache
