name: linkcheck
version: 2.0.0-dev.1  # Don't forget to update in lib/linkcheck.dart, too.

description: A very fast link-checker.

homepage: https://github.com/filiph/linkcheck
author: 'Filip Hracek <filip.hracek@gmail.com>'

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  args: ^1.4.3
  console: ^3.0.0
  csslib: ^0.14.1
  glob: ^1.1.5
  html: ^0.13.3
  logging: ^0.11.3+1
  path: ^1.5.1
  source_span: ^1.4.0

dev_dependencies:
  dhttpd: ^2.0.0
  test: ^0.12.34

executables:
  linkcheck: linkcheck

dependency_overrides:
  console:
    git:
      url: https://github.com/chalin/console.dart.git
      ref: chalin-dart-2-0612
  stream_channel:
    git: https://github.com/dart-lang/stream_channel.git
